include:
  - board: seeeduino_xiao_ble
    shield: clickety_split_pepito_left
  - board: seeeduino_xiao_ble
    shield: clickety_split_pepito_right
  - board: seeeduino_xiao_ble
    shield: settings_reset